<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="5.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Kernel\CMC.Kernel.Core\CMC.Kernel.Core.csproj" />
    <ProjectReference Include="..\..\Kernel\CMC.Kernel.Host.Base\CMC.Kernel.Host.Base.csproj" />
    <ProjectReference Include="..\CMC.Presentation.Application\CMC.Presentation.Application.csproj" />
  </ItemGroup>

</Project>
