<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="UAParser" Version="3.1.47" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CMC.Kernel.Core\CMC.Kernel.Core.csproj" />
    <ProjectReference Include="..\CMC.Kernel.Domain\CMC.Kernel.Domain.csproj" />
    <ProjectReference Include="..\CMC.Kernel.Infrastructure.Persistence\CMC.Kernel.Infrastructure.Persistence.csproj" />
  </ItemGroup>

</Project>
